package com.betai.domain.league;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum LeagueCode {
    PREMIER_LEAGUE("Premier League", "England", 1),
    LA_LIGA("La Liga", "Spain", 1),
    SERIE_A("Serie A", "Italy", 1),
    BUNDESLIGA("Bundesliga", "Germany", 1),
    LIGUE_1("Ligue 1", "France", 1),
    CHAMPIONSHIP("Championship", "England", 2),
    EREDIVISIE("Eredivisie", "Netherlands", 1),
    PRIMEIRA_LIGA("Primeira Liga", "Portugal", 1),
    BELGIAN_PRO_LEAGUE("Belgian Pro League", "Belgium", 1),
    SCOTTISH_PREMIERSHIP("Scottish Premiership", "Scotland", 1),
    SUPER_LIG("Super Lig", "Turkey", 1),
    ALLSVENSKAN("Allsvenskan", "Sweden", 1),
    ELITESERIEN("Eliteserien", "Norway", 1),
    FIFA_WORLD_CUP_2026("FIFA World Cup 2026", "International", 1),
    VEIKKAUSLIIGA("Veikkausliiga", "Finland", 1),
    LEAGUE_OF_IRELAND_PREMIER_DIVISION("League of Ireland Premier Division", "Ireland", 1),
    LEAGUE_OF_IRELAND_FIRST_DIVISION("League of Ireland First Division", "Ireland", 2),
    BESTA_DEILD("Besta deild", "Iceland", 1),
    MEISTRILIIGA("Meistriliiga", "Estonia", 1),
    TOPLYGA("TOPLYGA", "Lithuania", 1),
    LATVIAN_VIRSLIGA("Latvian Virsliga", "Latvia", 1),
    KAZAKHSTAN_PREMIER_LEAGUE("Kazakhstan Premier League", "Kazakhstan", 1),
    CHINESE_SUPER_LEAGUE("Chinese Super League", "China", 1),
    K_LEAGUE_1("K League 1", "South Korea", 1),
    K_LEAGUE_2("K League 2", "South Korea", 2),
    CANADIAN_PREMIER_LEAGUE("Canadian Premier League", "Canada", 1),
    BRAZILIAN_SERIE_B("Brazilian Serie B", "Brazil", 2),
    BRAZILIAN_SERIE_D("Brazilian Serie D", "Brazil", 4),
    UEFA_CHAMPIONS_LEAGUE("UEFA Champions League", "Europe", 1),
    UEFA_EUROPA_LEAGUE("UEFA Europa League", "Europe", 1),
    UEFA_EUROPA_CONFERENCE_LEAGUE("UEFA Europa Conference League", "Europe", 1),
    FA_CUP("FA Cup", "England", 1),
    EFL_CUP("EFL Cup", "England", 1),
    COPA_DEL_REY("Copa del Rey", "Spain", 1),
    COPPA_ITALIA("Coppa Italia", "Italy", 1),
    DFB_POKAL("DFB-Pokal", "Germany", 1),
    COUPE_DE_FRANCE("Coupe de France", "France", 1),
    DANISH_SUPERLIGA("Danish Superliga", "Denmark", 1),
    SWISS_SUPER_LEAGUE("Swiss Super League", "Switzerland", 1),
    AUSTRIAN_BUNDESLIGA("Austrian Bundesliga", "Austria", 1),
    POLISH_EKSTRAKLASA("Polish Ekstraklasa", "Poland", 1),
    CZECH_FIRST_LEAGUE("Czech First League", "Czechia", 1),
    CROATIAN_FOOTBALL_LEAGUE("Croatian Football League", "Croatia", 1),
    SERBIAN_SUPERLIGA("Serbian SuperLiga", "Serbia", 1),
    ROMANIAN_LIGA_I("Romanian Liga I", "Romania", 1),
    GREEK_SUPER_LEAGUE("Greek Super League", "Greece", 1),
    UKRAINIAN_PREMIER_LEAGUE("Ukrainian Premier League", "Ukraine", 1),
    SLOVAK_FIRST_LEAGUE("Slovak First Football League", "Slovakia", 1),
    LIGA_MX("Liga MX", "Mexico", 1),
    MLS("Major League Soccer", "United States", 1),
    USL_CHAMPIONSHIP("USL Championship", "United States", 2),
    ARGENTINE_PRIMERA_DIVISION("Argentine Primera Division", "Argentina", 1),
    COPA_LIBERTADORES("Copa Libertadores", "South America", 1),
    COPA_SUDAMERICANA("Copa Sudamericana", "South America", 1),
    BRAZILIAN_SERIE_A("Brazilian Serie A", "Brazil", 1),
    BRAZILIAN_SERIE_C("Brazilian Serie C", "Brazil", 3),
    CHILEAN_PRIMERA_DIVISION("Chilean Primera Division", "Chile", 1),
    COLOMBIAN_PRIMERA_A("Colombian Primera A", "Colombia", 1),
    PERUVIAN_LIGA_1("Peruvian Liga 1", "Peru", 1),
    URUGUAYAN_PRIMERA_DIVISION("Uruguayan Primera Division", "Uruguay", 1),
    PARAGUAYAN_PRIMERA_DIVISION("Paraguayan Primera Division", "Paraguay", 1),
    ECUADORIAN_SERIE_A("Ecuadorian Serie A", "Ecuador", 1),
    SAUDI_PRO_LEAGUE("Saudi Pro League", "Saudi Arabia", 1),
    UAE_PRO_LEAGUE("UAE Pro League", "United Arab Emirates", 1),
    QATAR_STARS_LEAGUE("Qatar Stars League", "Qatar", 1),
    J1_LEAGUE("J1 League", "Japan", 1),
    J2_LEAGUE("J2 League", "Japan", 2),
    A_LEAGUE_MEN("A-League Men", "Australia", 1),
    THAI_LEAGUE_1("Thai League 1", "Thailand", 1),
    INDIAN_SUPER_LEAGUE("Indian Super League", "India", 1),
    INDONESIAN_LIGA_1("Indonesian Liga 1", "Indonesia", 1),
    UZBEKISTAN_SUPER_LEAGUE("Uzbekistan Super League", "Uzbekistan", 1),
    EGYPTIAN_PREMIER_LEAGUE("Egyptian Premier League", "Egypt", 1),
    SOUTH_AFRICAN_PREMIER_DIVISION("South African Premier Division", "South Africa", 1),
    MOROCCAN_BOTOLA_PRO("Moroccan Botola Pro", "Morocco", 1),
    TUNISIAN_LIGUE_1("Tunisian Ligue Professionnelle 1", "Tunisia", 1),
    CAF_CHAMPIONS_LEAGUE("CAF Champions League", "Africa", 1),
    NIGERIAN_PREMIER_FOOTBALL_LEAGUE("Nigerian Premier Football League", "Nigeria", 1),
    RUSSIAN_FOOTBALL_PREMIER_LEAGUE("Russian Football Premier League", "Russia", 1),
    ITALIAN_SERIE_B("Italian Serie B", "Italy", 2),
    SCOTTISH_CHAMPIONSHIP("Scottish Championship", "Scotland", 2),
    ENGLISH_LEAGUE_1("English League 1", "England", 1),
    ENGLISH_LEAGUE_2("English League 2", "England", 1),
    ITALIAN_SERIE_C_GIRONE_C("Italian Serie C Girone C", "Italy", 3),
    GERMAN_2_BUNDESLIGA("German 2. Bundesliga", "Germany", 1),
    SPANISH_LA_LIGA_2("Spanish La Liga 2", "Spain", 2),
    FRENCH_LIGUE_2("French Ligue 2", "France", 1),
    SWEDISH_SUPERETTAN("Swedish Superettan", "Sweden", 2),
    NORWEGIAN_1_DIVISJON("Norwegian 1. Divisjon", "Norway", 1),
    WELSH_PREMIER_LEAGUE("Welsh Premier League", "Wales", 1),
    UEFA_NATIONS_LEAGUE("UEFA Nations League", "Europe", 1),
    AFRICAN_CUP_OF_NATIONS("African Cup of Nations", "Worldwide", 1),
    COPA_ARGENTINA("Copa Argentina", "Argentina", 1),
    FIFA_CLUB_WORLD_CUP("FIFA Club World Cup", "Worldwide", 1),
    SUPERCOPPA_ITALIANA("Supercoppa Italiana", "Italy", 1),
    TACA_DE_LIGA("Taca de Liga", "Portugal", 1),
    TACA_DE_PORTUGAL("Taca de Portugal", "Portugal", 1),
    SUPERCOPA_DE_ESPANA("Supercopa de Espana", "Spain", 1),
    UEFA_SUPER_CUP("UEFA Super Cup", "Europe", 1),
    VENEZUELA_PRIMERA_DIVISION("Venezuela Primera Division", "Venezuela", 1),
    AMERICAN_NWSL("American NWSL", "United States", 1),
    INTERNATIONAL_FRIENDLIES("International Friendlies", "Worldwide", 1),
    UEFA_EUROPEAN_UNDER_21_CHAMPIONSHIP("UEFA European Under-21 Championship", "Europe", 2),
    CLUB_FRIENDLIES("Club Friendlies", "Worldwide", 1),
    FA_COMMUNITY_SHIELD("FA Community Shield", "United Kingdom", 1),
    ENGLISH_NATIONAL_LEAGUE("English National League", "England", 2),
    ARGENTINIAN_PRIMERA_B_NACIONAL("Argentinian Primera B Nacional", "Argentina", 1),
    ALBANIAN_SUPERLIGA("Albanian Superliga", "Albania", 1),
    ANDORRAN_1A_DIVISIO("Andorran 1a Divisio", "Andorra", 1),
    ARMENIAN_PREMIER_LEAGUE("Armenian Premier League", "Armenia", 1),
    AUSTRALIA_ACT_NPL("Australia ACT NPL", "Australia", 1),
    BELARUS_VYSCHA_LIGA("Belarus Vyscha Liga", "Belarus", 1),
    BELGIAN_CHALLENGER_PRO_LEAGUE("Belgian Challenger Pro League", "Belgium", 1),
    BOSNIAN_PREMIER_LIGA("Bosnian Premier Liga", "Bosnia and Herzegovina", 1),
    BULGARIAN_FIRST_LEAGUE("Bulgarian First League", "Bulgaria", 1),
    CHINA_LEAGUE_ONE("China League One", "China", 3),
    CYPRIOT_FIRST_DIVISION("Cypriot First Division", "Cyprus", 1),
    DANISH_2ND_DIVISION("Danish 2nd Division", "Denmark", 2),
    FAROE_ISLANDS_PREMIER_LEAGUE("Faroe Islands Premier League", "Faroe Islands", 1),
    FRENCH_LIGUE_3("French Ligue 3", "France", 1),
    GEORGIAN_EROVNULI_LIGA("Georgian Erovnuli Liga", "Georgia", 1),
    GERMANY_LIGA_3("Germany Liga 3", "Germany", 3),
    GREEK_SUPER_LEAGUE_2("Greek Super League 2", "Greece", 1),
    DUTCH_EERSTE_DIVISIE("Dutch Eerste Divisie", "The Netherlands", 1),
    ISRAELI_PREMIER_LEAGUE("Israeli Premier League", "Israel", 1),
    ITALY_SERIE_D_GIRONE_D("Italy Serie D Girone D", "Italy", 4),
    ENGLISH_NORTHERN_PREMIER_LEAGUE_PREMIER_DIVISION("English Northern Premier League Premier Division", "England", 1),
    ENGLISH_ISTHMIAN_LEAGUE_PREMIER_DIVISION("English Isthmian League Premier Division", "England", 1),
    ENGLISH_SOUTHERN_PREMIER_LEAGUE_SOUTH_DIVISION("English Southern Premier League South Division", "England", 1),
    MACEDONIAN_FIRST_LEAGUE("Macedonian First League", "Macedonia", 1),
    MALTESE_PREMIER_LEAGUE("Maltese Premier League", "Malta", 1),
    MEXICAN_LIGA_DE_EXPANSION_MX("Mexican Liga de Expansion MX", "Mexico", 1),
    MOLDOVAN_NATIONAL_DIVISION("Moldovan National Division", "Moldova", 1),
    MONTENEGRIN_FIRST_LEAGUE("Montenegrin First League", "Montenegro", 1),
    MOROCCAN_BOTOLA_2("Moroccan Botola 2", "Morocco", 1),
    NORTHERN_IRISH_PREMIERSHIP("Northern Irish Premiership", "Northern Ireland", 1),
    POLISH_I_LIGA("Polish I liga", "Poland", 1),
    PORTUGUESE_LIGAPRO("Portuguese LigaPro", "Portugal", 1),
    ROMANIAN_LIGA_II("Romanian Liga II", "Romania", 1),
    RUSSIAN_FOOTBALL_NATIONAL_LEAGUE("Russian Football National League", "Russia", 2),
    SAN_MARINO_CAMPIONATO("San-Marino Campionato", "San Marino", 1),
    SCOTTISH_LEAGUE_1("Scottish League 1", "Scotland", 1),
    SCOTTISH_LEAGUE_2("Scottish League 2", "Scotland", 1),
    SWEDISH_DIVISION_1_NORTH("Swedish Division 1 North", "Sweden", 1),
    TURKISH_1_LIG("Turkish 1 Lig", "Turkey", 1),
    UKRAINIAN_FIRST_LEAGUE("Ukrainian First League", "Ukraine", 1),
    TURKISH_2_LIG("Turkish 2 Lig", "Turkey", 1),
    ENGLISH_NATIONAL_LEAGUE_NORTH("English National League North", "England", 2),
    ENGLISH_NATIONAL_LEAGUE_SOUTH("English National League South", "England", 2),
    DANISH_1ST_DIVISION("Danish 1st Division", "Denmark", 1),
    BOLIVIAN_PRIMERA_DIVISION("Bolivian Primera Division", "Bolivia", 1),
    HUNGARIAN_NB_I("Hungarian NB I", "Hungary", 1),
    SLOVENIAN_1_SNL("Slovenian 1. SNL", "Slovenia", 1),
    AZERBAIJANI_PREMIER_LEAGUE("Azerbaijani Premier League", "Azerbaijan", 1),
    LUXEMBOURG_NATIONAL_DIVISION("Luxembourg National Division", "Luxembourg", 1),
    GERMAN_REGIONALLIGA_NORD("German Regionalliga Nord", "Germany", 1),
    SWISS_CHALLENGE_LEAGUE("Swiss Challenge League", "Switzerland", 2),
    AFC_CHAMPIONS_LEAGUE_ELITE("AFC Champions League Elite", "Worldwide", 1),
    CONCACAF_CHAMPIONS_CUP("CONCACAF Champions Cup", "Worldwide", 1),
    SCOTTISH_FA_CUP("Scottish FA Cup", "Scotland", 1),
    COPA_DO_BRASIL("Copa do Brasil", "Brazil", 1),
    CONCACAF_CENTRAL_AMERICAN_CUP("CONCACAF Central American Cup", "Worldwide", 1),
    IRANIAN_AZADEGAN_LEAGUE("Iranian Azadegan League", "Iran", 1),
    IRANIAN_PERSIAN_GULF_PRO_LEAGUE("Iranian Persian Gulf Pro League", "Iran", 1),
    THAI_LEAGUE_2("Thai League 2", "Thailand", 1),
    KENYAN_PREMIER_LEAGUE("Kenyan Premier League", "Kenya", 1),
    GERMAN_REGIONALLIGA_WEST("German Regionalliga West", "Germany", 1),
    GERMAN_REGIONALLIGA_SUDWEST("German Regionalliga SudWest", "Germany", 1),
    GERMAN_REGIONALLIGA_BAYERN("German Regionalliga Bayern", "Germany", 1),
    GERMAN_REGIONALLIGA_NORDOST("German Regionalliga Nordost", "Germany", 1),
    ALGERIAN_LIGUE_1("Algerian Ligue 1", "Algeria", 1),
    SENEGAL_LIGUE_1("Senegal Ligue 1", "Senegal", 1),
    NORTHERN_IRISH_CHAMPIONSHIP("Northern Irish Championship", "Northern Ireland", 2),
    SVENSKA_CUPEN("Svenska Cupen", "Sweden", 1),
    ITALY_SERIE_D_GIRONE_B("Italy Serie D Girone B", "Italy", 4),
    ITALY_SERIE_D_GIRONE_C("Italy Serie D Girone C", "Italy", 4),
    ITALY_SERIE_D_GIRONE_E("Italy Serie D Girone E", "Italy", 4),
    ITALY_SERIE_D_GIRONE_F("Italy Serie D Girone F", "Italy", 4);

    private final String displayName;
    private final String country;
    private final int tier;

    public boolean isLeagueCompetition() {
        return switch (this) {
            case FIFA_WORLD_CUP_2026,
                 UEFA_CHAMPIONS_LEAGUE,
                 UEFA_EUROPA_LEAGUE,
                 UEFA_EUROPA_CONFERENCE_LEAGUE,
                 FA_CUP,
                 EFL_CUP,
                 COPA_DEL_REY,
                 COPPA_ITALIA,
                 DFB_POKAL,
                 COUPE_DE_FRANCE,
                 COPA_LIBERTADORES,
                 COPA_SUDAMERICANA,
                 CAF_CHAMPIONS_LEAGUE,
                 UEFA_NATIONS_LEAGUE,
                 AFRICAN_CUP_OF_NATIONS,
                 COPA_ARGENTINA,
                 FIFA_CLUB_WORLD_CUP,
                 SUPERCOPPA_ITALIANA,
                 TACA_DE_LIGA,
                 TACA_DE_PORTUGAL,
                 SUPERCOPA_DE_ESPANA,
                 UEFA_SUPER_CUP,
                 INTERNATIONAL_FRIENDLIES,
                 UEFA_EUROPEAN_UNDER_21_CHAMPIONSHIP,
                 CLUB_FRIENDLIES,
                 FA_COMMUNITY_SHIELD,
                 AFC_CHAMPIONS_LEAGUE_ELITE,
                 CONCACAF_CHAMPIONS_CUP,
                 SCOTTISH_FA_CUP,
                 COPA_DO_BRASIL,
                 CONCACAF_CENTRAL_AMERICAN_CUP,
                 SVENSKA_CUPEN -> false;
            default -> true;
        };
    }
}
