with sharpapi_targets(code, sport_key) as (
    values
    ('PREMIER_LEAGUE', 'england_-_premier_league'),
    ('CHAMPIONSHIP', 'england_-_championship'),
    ('LA_LIGA', 'spain_-_la_liga'),
    ('SERIE_A', 'italy_-_serie_a'),
    ('BUNDESLIGA', 'germany_-_bundesliga'),
    ('LIGUE_1', 'france_-_ligue_1'),
    ('EREDIVISIE', 'netherlands_-_eredivisie'),
    ('SCOTTISH_PREMIERSHIP', 'scotland_-_premiership'),
    ('ALLSVENSKAN', 'sweden_-_allsvenskan'),
    ('ELITESERIEN', 'norway_-_eliteserien'),
    ('VEIKKAUSLIIGA', 'finland_-_veikkausliiga'),
    ('LEAGUE_OF_IRELAND_PREMIER_DIVISION', 'ireland_premier_division'),
    ('LEAGUE_OF_IRELAND_FIRST_DIVISION', 'ireland_-_division_1'),
    ('BESTA_DEILD', 'besta_deild'),
    ('MEISTRILIIGA', 'estonia_-_premium_liiga'),
    ('TOPLYGA', 'lithuania_-_top_liga'),
    ('LATVIAN_VIRSLIGA', 'latvia_-_virsliga'),
    ('KAZAKHSTAN_PREMIER_LEAGUE', 'kazakhstan_-_premier_league'),
    ('CHINESE_SUPER_LEAGUE', 'china_-_super_league'),
    ('K_LEAGUE_1', 'republic_of_korea_-_k_league_1'),
    ('K_LEAGUE_2', 'korea_-_k2_league'),
    ('CANADIAN_PREMIER_LEAGUE', 'canada_-_canadian_premier_league'),
    ('BRAZILIAN_SERIE_B', 'brazil_-_serie_b'),
    ('BRAZILIAN_SERIE_D', 'brazil_-_serie_d'),
    ('FIFA_WORLD_CUP_2026', 'fifa_-_world_cup'),
    ('UEFA_CHAMPIONS_LEAGUE', 'uefa_-_champions_league'),
    ('UEFA_EUROPA_LEAGUE', 'uefa_-_europa_league'),
    ('UEFA_EUROPA_CONFERENCE_LEAGUE', 'uefa_-_europa_conference_league'),
    ('FA_CUP', 'england_-_fa_cup'),
    ('EFL_CUP', 'england_-_efl_cup'),
    ('DFB_POKAL', 'germany_-_dfb_pokal'),
    ('SWISS_SUPER_LEAGUE', 'switzerland_-_super_league'),
    ('MLS', 'usa_-_major_league_soccer'),
    ('USL_CHAMPIONSHIP', 'usa_-_usl_championship'),
    ('ARGENTINE_PRIMERA_DIVISION', 'argentina_-_primera_division'),
    ('COPA_LIBERTADORES', 'conmebol_-_copa_libertadores'),
    ('COPA_SUDAMERICANA', 'conmebol_-_copa_sudamericana'),
    ('BRAZILIAN_SERIE_A', 'brazil_-_serie_a'),
    ('BRAZILIAN_SERIE_C', 'brazil_-_serie_c'),
    ('CHILEAN_PRIMERA_DIVISION', 'chile_-_primera_division'),
    ('URUGUAYAN_PRIMERA_DIVISION', 'uruguay_-_primera_division'),
    ('ECUADORIAN_SERIE_A', 'ecuador_-_serie_a'),
    ('SAUDI_PRO_LEAGUE', 'saudi_arabia_-_saudi_league'),
    ('MOROCCAN_BOTOLA_PRO', 'morocco_-_botola_pro')
), active_state(active) as (
    select coalesce(bool_or(st.active), true)
    from source_targets st
    where st.source_type = 'ODDS_REFERENCE'
      and st.name like 'SharpAPI Upcoming Odds%'
)
insert into source_targets (
    id,
    league_id,
    source_type,
    name,
    url_template,
    source_season_token,
    target_season_label,
    render_mode,
    active,
    robots_txt_required,
    user_agent,
    rate_limit_per_minute,
    timeout_ms,
    reliability_score,
    fallback_priority,
    selectors_json,
    last_success_at,
    last_failure_at,
    consecutive_failures,
    last_failure_reason,
    system_disabled,
    quarantined_until,
    created_at,
    updated_at
)
select
    gen_random_uuid(),
    l.id,
    'ODDS_REFERENCE',
    'SharpAPI Upcoming Odds ' || l.name || ' JSON',
    '{sharpApiBaseUrl}/odds?league=' || t.sport_key || '&limit=200',
    null,
    l.current_season,
    'STATIC_HTML',
    a.active,
    false,
    'BetAIResearchBot/0.1 (+local-development)',
    12,
    20000,
    92.00,
    5,
    '{"format":"sharpapi-odds-json","sportKey":"' || t.sport_key || '","includeOneXTwo":true,"includeOverUnder25":true}',
    null,
    null,
    0,
    null,
    false,
    null,
    now(),
    now()
from sharpapi_targets t
join leagues l on l.code = t.code
cross join active_state a
on conflict (league_id, source_type, name) do update
set url_template = excluded.url_template,
    target_season_label = excluded.target_season_label,
    render_mode = excluded.render_mode,
    active = excluded.active,
    robots_txt_required = excluded.robots_txt_required,
    user_agent = excluded.user_agent,
    rate_limit_per_minute = excluded.rate_limit_per_minute,
    timeout_ms = excluded.timeout_ms,
    reliability_score = excluded.reliability_score,
    fallback_priority = excluded.fallback_priority,
    selectors_json = excluded.selectors_json,
    consecutive_failures = 0,
    last_failure_reason = null,
    system_disabled = false,
    quarantined_until = null,
    updated_at = now();
