with verified_leagues(
    code,
    display_name,
    country,
    tier,
    current_season,
    external_id,
    external_name
) as (
    values
    ('RUSSIAN_FOOTBALL_PREMIER_LEAGUE', 'Russian Football Premier League', 'Russia', 1, '2026/2027', '4355', 'Russian Football Premier League'),
    ('ITALIAN_SERIE_B', 'Italian Serie B', 'Italy', 2, '2025/2026', '4394', 'Italian Serie B'),
    ('SCOTTISH_CHAMPIONSHIP', 'Scottish Championship', 'Scotland', 2, '2026/2027', '4395', 'Scottish Championship'),
    ('ENGLISH_LEAGUE_1', 'English League 1', 'England', 1, '2026/2027', '4396', 'English League 1'),
    ('ENGLISH_LEAGUE_2', 'English League 2', 'England', 1, '2026/2027', '4397', 'English League 2'),
    ('ITALIAN_SERIE_C_GIRONE_C', 'Italian Serie C Girone C', 'Italy', 3, '2025/2026', '4398', 'Italian Serie C Girone C'),
    ('GERMAN_2_BUNDESLIGA', 'German 2. Bundesliga', 'Germany', 1, '2026/2027', '4399', 'German 2. Bundesliga'),
    ('SPANISH_LA_LIGA_2', 'Spanish La Liga 2', 'Spain', 2, '2026/2027', '4400', 'Spanish La Liga 2'),
    ('FRENCH_LIGUE_2', 'French Ligue 2', 'France', 1, '2026/2027', '4401', 'French Ligue 2'),
    ('SWEDISH_SUPERETTAN', 'Swedish Superettan', 'Sweden', 2, '2026', '4403', 'Swedish Superettan'),
    ('NORWEGIAN_1_DIVISJON', 'Norwegian 1. Divisjon', 'Norway', 1, '2026', '4457', 'Norwegian 1. Divisjon'),
    ('WELSH_PREMIER_LEAGUE', 'Welsh Premier League', 'Wales', 1, '2026/2027', '4472', 'Welsh Premier League'),
    ('UEFA_NATIONS_LEAGUE', 'UEFA Nations League', 'Europe', 1, '2026/2027', '4490', 'UEFA Nations League'),
    ('AFRICAN_CUP_OF_NATIONS', 'African Cup of Nations', 'Worldwide', 1, '2025', '4496', 'African Cup of Nations'),
    ('COPA_ARGENTINA', 'Copa Argentina', 'Argentina', 1, '2026', '4500', 'Copa Argentina'),
    ('FIFA_CLUB_WORLD_CUP', 'FIFA Club World Cup', 'Worldwide', 1, '2025', '4503', 'FIFA Club World Cup'),
    ('SUPERCOPPA_ITALIANA', 'Supercoppa Italiana', 'Italy', 1, '2025', '4507', 'Supercoppa Italiana'),
    ('TACA_DE_LIGA', 'Taca de Liga', 'Portugal', 1, '2025/2026', '4509', 'Taca de Liga'),
    ('TACA_DE_PORTUGAL', 'Taca de Portugal', 'Portugal', 1, '2025/2026', '4510', 'Taca de Portugal'),
    ('SUPERCOPA_DE_ESPANA', 'Supercopa de Espana', 'Spain', 1, '2025/2026', '4511', 'Supercopa de Espana'),
    ('UEFA_SUPER_CUP', 'UEFA Super Cup', 'Europe', 1, '2026', '4512', 'UEFA Super Cup'),
    ('VENEZUELA_PRIMERA_DIVISION', 'Venezuela Primera Division', 'Venezuela', 1, '2026', '4513', 'Venezuela Primera Division'),
    ('AMERICAN_NWSL', 'American NWSL', 'United States', 1, '2026', '4521', 'American NWSL'),
    ('INTERNATIONAL_FRIENDLIES', 'International Friendlies', 'Worldwide', 1, '2026', '4562', 'International Friendlies'),
    ('UEFA_EUROPEAN_UNDER_21_CHAMPIONSHIP', 'UEFA European Under-21 Championship', 'Europe', 2, '2025/2026', '4566', 'UEFA European Under-21 Championship'),
    ('CLUB_FRIENDLIES', 'Club Friendlies', 'Worldwide', 1, '2026', '4569', 'Club Friendlies'),
    ('FA_COMMUNITY_SHIELD', 'FA Community Shield', 'United Kingdom', 1, '2026', '4571', 'FA Community Shield'),
    ('ENGLISH_NATIONAL_LEAGUE', 'English National League', 'England', 2, '2025/2026', '4590', 'English National League'),
    ('ARGENTINIAN_PRIMERA_B_NACIONAL', 'Argentinian Primera B Nacional', 'Argentina', 1, '2026', '4616', 'Argentinian Primera B Nacional'),
    ('ALBANIAN_SUPERLIGA', 'Albanian Superliga', 'Albania', 1, '2025/2026', '4617', 'Albanian Superliga'),
    ('ANDORRAN_1A_DIVISIO', 'Andorran 1a Divisio', 'Andorra', 1, '2025/2026', '4618', 'Andorran 1a Divisio'),
    ('ARMENIAN_PREMIER_LEAGUE', 'Armenian Premier League', 'Armenia', 1, '2025/2026', '4619', 'Armenian Premier League'),
    ('AUSTRALIA_ACT_NPL', 'Australia ACT NPL', 'Australia', 1, '2026', '4620', 'Australia ACT NPL'),
    ('BELARUS_VYSCHA_LIGA', 'Belarus Vyscha Liga', 'Belarus', 1, '2026', '4622', 'Belarus Vyscha Liga'),
    ('BELGIAN_CHALLENGER_PRO_LEAGUE', 'Belgian Challenger Pro League', 'Belgium', 1, '2026/2027', '4623', 'Belgian Challenger Pro League'),
    ('BOSNIAN_PREMIER_LIGA', 'Bosnian Premier Liga', 'Bosnia and Herzegovina', 1, '2025/2026', '4624', 'Bosnian Premier Liga'),
    ('BULGARIAN_FIRST_LEAGUE', 'Bulgarian First League', 'Bulgaria', 1, '2026/2027', '4626', 'Bulgarian First League'),
    ('CHINA_LEAGUE_ONE', 'China League One', 'China', 3, '2026', '4628', 'China League One'),
    ('CYPRIOT_FIRST_DIVISION', 'Cypriot First Division', 'Cyprus', 1, '2025/2026', '4630', 'Cypriot First Division'),
    ('DANISH_2ND_DIVISION', 'Danish 2nd Division', 'Denmark', 2, '2026/2027', '4632', 'Danish 2nd Division'),
    ('FAROE_ISLANDS_PREMIER_LEAGUE', 'Faroe Islands Premier League', 'Faroe Islands', 1, '2026', '4635', 'Faroe Islands Premier League'),
    ('FRENCH_LIGUE_3', 'French Ligue 3', 'France', 1, '2026/2027', '4637', 'French Ligue 3'),
    ('GEORGIAN_EROVNULI_LIGA', 'Georgian Erovnuli Liga', 'Georgia', 1, '2026', '4638', 'Georgian Erovnuli Liga'),
    ('GERMANY_LIGA_3', 'Germany Liga 3', 'Germany', 3, '2025/2026', '4639', 'Germany Liga 3'),
    ('GREEK_SUPER_LEAGUE_2', 'Greek Super League 2', 'Greece', 1, '2025/2026', '4640', 'Greek Super League 2'),
    ('DUTCH_EERSTE_DIVISIE', 'Dutch Eerste Divisie', 'The Netherlands', 1, '2026/2027', '4641', 'Dutch Eerste Divisie'),
    ('ISRAELI_PREMIER_LEAGUE', 'Israeli Premier League', 'Israel', 1, '2026/2027', '4644', 'Israeli Premier League'),
    ('ITALY_SERIE_D_GIRONE_D', 'Italy Serie D Girone D', 'Italy', 4, '2025/2026', '4645', 'Italy Serie D Girone D'),
    ('ENGLISH_NORTHERN_PREMIER_LEAGUE_PREMIER_DIVISION', 'English Northern Premier League Premier Division', 'England', 1, '2025/2026', '4646', 'English Northern Premier League Premier Division'),
    ('ENGLISH_ISTHMIAN_LEAGUE_PREMIER_DIVISION', 'English Isthmian League Premier Division', 'England', 1, '2025/2026', '4647', 'English Isthmian League Premier Division'),
    ('ENGLISH_SOUTHERN_PREMIER_LEAGUE_SOUTH_DIVISION', 'English Southern Premier League South Division', 'England', 1, '2025/2026', '4648', 'English Southern Premier League South Division'),
    ('MACEDONIAN_FIRST_LEAGUE', 'Macedonian First League', 'Macedonia', 1, '2026/2027', '4652', 'Macedonian First League'),
    ('MALTESE_PREMIER_LEAGUE', 'Maltese Premier League', 'Malta', 1, '2026/2027', '4653', 'Maltese Premier League'),
    ('MEXICAN_LIGA_DE_EXPANSION_MX', 'Mexican Liga de Expansion MX', 'Mexico', 1, '2025/2026', '4654', 'Mexican Liga de Expansion MX'),
    ('MOLDOVAN_NATIONAL_DIVISION', 'Moldovan National Division', 'Moldova', 1, '2026/2027', '4655', 'Moldovan National Division'),
    ('MONTENEGRIN_FIRST_LEAGUE', 'Montenegrin First League', 'Montenegro', 1, '2026/2027', '4656', 'Montenegrin First League'),
    ('MOROCCAN_BOTOLA_2', 'Moroccan Botola 2', 'Morocco', 1, '2025/2026', '4657', 'Moroccan Botola 2'),
    ('NORTHERN_IRISH_PREMIERSHIP', 'Northern Irish Premiership', 'Northern Ireland', 1, '2026/2027', '4659', 'Northern Irish Premiership'),
    ('POLISH_I_LIGA', 'Polish I liga', 'Poland', 1, '2026/2027', '4661', 'Polish I liga'),
    ('PORTUGUESE_LIGAPRO', 'Portuguese LigaPro', 'Portugal', 1, '2026/2027', '4662', 'Portuguese LigaPro'),
    ('ROMANIAN_LIGA_II', 'Romanian Liga II', 'Romania', 1, '2025/2026', '4665', 'Romanian Liga II'),
    ('RUSSIAN_FOOTBALL_NATIONAL_LEAGUE', 'Russian Football National League', 'Russia', 2, '2026/2027', '4666', 'Russian Football National League'),
    ('SAN_MARINO_CAMPIONATO', 'San-Marino Campionato', 'San Marino', 1, '2025/2026', '4667', 'San-Marino Campionato'),
    ('SCOTTISH_LEAGUE_1', 'Scottish League 1', 'Scotland', 1, '2026/2027', '4669', 'Scottish League 1'),
    ('SCOTTISH_LEAGUE_2', 'Scottish League 2', 'Scotland', 1, '2026/2027', '4670', 'Scottish League 2'),
    ('SWEDISH_DIVISION_1_NORTH', 'Swedish Division 1 North', 'Sweden', 1, '2026', '4674', 'Swedish Division 1 North'),
    ('TURKISH_1_LIG', 'Turkish 1 Lig', 'Turkey', 1, '2025/2026', '4676', 'Turkish 1 Lig'),
    ('UKRAINIAN_FIRST_LEAGUE', 'Ukrainian First League', 'Ukraine', 1, '2025/2026', '4677', 'Ukrainian First League'),
    ('TURKISH_2_LIG', 'Turkish 2 Lig', 'Turkey', 1, '2025/2026', '4679', 'Turkish 2 Lig'),
    ('ENGLISH_NATIONAL_LEAGUE_NORTH', 'English National League North', 'England', 2, '2025/2026', '4681', 'English National League North'),
    ('ENGLISH_NATIONAL_LEAGUE_SOUTH', 'English National League South', 'England', 2, '2025/2026', '4682', 'English National League South'),
    ('DANISH_1ST_DIVISION', 'Danish 1st Division', 'Denmark', 1, '2026/2027', '4683', 'Danish 1st Division'),
    ('BOLIVIAN_PRIMERA_DIVISION', 'Bolivian Primera Division', 'Bolivia', 1, '2026', '4685', 'Bolivian Primera Division'),
    ('HUNGARIAN_NB_I', 'Hungarian NB I', 'Hungary', 1, '2026/2027', '4690', 'Hungarian NB I'),
    ('SLOVENIAN_1_SNL', 'Slovenian 1. SNL', 'Slovenia', 1, '2026/2027', '4692', 'Slovenian 1. SNL'),
    ('AZERBAIJANI_PREMIER_LEAGUE', 'Azerbaijani Premier League', 'Azerbaijan', 1, '2025/2026', '4693', 'Azerbaijani Premier League'),
    ('LUXEMBOURG_NATIONAL_DIVISION', 'Luxembourg National Division', 'Luxembourg', 1, '2025/2026', '4694', 'Luxembourg National Division'),
    ('GERMAN_REGIONALLIGA_NORD', 'German Regionalliga Nord', 'Germany', 1, '2025/2026', '4695', 'German Regionalliga Nord'),
    ('SWISS_CHALLENGE_LEAGUE', 'Swiss Challenge League', 'Switzerland', 2, '2026/2027', '4713', 'Swiss Challenge League'),
    ('AFC_CHAMPIONS_LEAGUE_ELITE', 'AFC Champions League Elite', 'Worldwide', 1, '2026/2027', '4719', 'AFC Champions League Elite'),
    ('CONCACAF_CHAMPIONS_CUP', 'CONCACAF Champions Cup', 'Worldwide', 1, '2026', '4721', 'CONCACAF Champions Cup'),
    ('SCOTTISH_FA_CUP', 'Scottish FA Cup', 'Scotland', 1, '2025/2026', '4723', 'Scottish FA Cup'),
    ('COPA_DO_BRASIL', 'Copa do Brasil', 'Brazil', 1, '2026', '4725', 'Copa do Brasil'),
    ('CONCACAF_CENTRAL_AMERICAN_CUP', 'CONCACAF Central American Cup', 'Worldwide', 1, '2026', '4739', 'CONCACAF Central American Cup'),
    ('IRANIAN_AZADEGAN_LEAGUE', 'Iranian Azadegan League', 'Iran', 1, '2025/2026', '4741', 'Iranian Azadegan League'),
    ('IRANIAN_PERSIAN_GULF_PRO_LEAGUE', 'Iranian Persian Gulf Pro League', 'Iran', 1, '2025/2026', '4742', 'Iranian Persian Gulf Pro League'),
    ('THAI_LEAGUE_2', 'Thai League 2', 'Thailand', 1, '2025/2026', '4744', 'Thai League 2'),
    ('KENYAN_PREMIER_LEAGUE', 'Kenyan Premier League', 'Kenya', 1, '2025/2026', '4745', 'Kenyan Premier League'),
    ('GERMAN_REGIONALLIGA_WEST', 'German Regionalliga West', 'Germany', 1, '2025/2026', '4746', 'German Regionalliga West'),
    ('GERMAN_REGIONALLIGA_SUDWEST', 'German Regionalliga SudWest', 'Germany', 1, '2025/2026', '4747', 'German Regionalliga SudWest'),
    ('GERMAN_REGIONALLIGA_BAYERN', 'German Regionalliga Bayern', 'Germany', 1, '2025/2026', '4748', 'German Regionalliga Bayern'),
    ('GERMAN_REGIONALLIGA_NORDOST', 'German Regionalliga Nordost', 'Germany', 1, '2025/2026', '4749', 'German Regionalliga Nordost'),
    ('ALGERIAN_LIGUE_1', 'Algerian Ligue 1', 'Algeria', 1, '2025/2026', '4753', 'Algerian Ligue 1'),
    ('SENEGAL_LIGUE_1', 'Senegal Ligue 1', 'Senegal', 1, '2025/2026', '4754', 'Senegal Ligue 1'),
    ('NORTHERN_IRISH_CHAMPIONSHIP', 'Northern Irish Championship', 'Northern Ireland', 2, '2026/2027', '4755', 'Northern Irish Championship'),
    ('SVENSKA_CUPEN', 'Svenska Cupen', 'Sweden', 1, '2026/2027', '4756', 'Svenska Cupen'),
    ('ITALY_SERIE_D_GIRONE_B', 'Italy Serie D Girone B', 'Italy', 4, '2025/2026', '4778', 'Italy Serie D Girone B'),
    ('ITALY_SERIE_D_GIRONE_C', 'Italy Serie D Girone C', 'Italy', 4, '2025/2026', '4779', 'Italy Serie D Girone C'),
    ('ITALY_SERIE_D_GIRONE_E', 'Italy Serie D Girone E', 'Italy', 4, '2025/2026', '4780', 'Italy Serie D Girone E'),
    ('ITALY_SERIE_D_GIRONE_F', 'Italy Serie D Girone F', 'Italy', 4, '2025/2026', '4782', 'Italy Serie D Girone F')
)
insert into leagues (
    id,
    code,
    name,
    country,
    tier,
    active,
    scrape_enabled,
    current_season,
    created_at,
    updated_at
)
select
    gen_random_uuid(),
    code,
    display_name,
    country,
    tier,
    true,
    false,
    current_season,
    now(),
    now()
from verified_leagues
on conflict (code) do update
set name = excluded.name,
    country = excluded.country,
    tier = excluded.tier,
    current_season = excluded.current_season,
    updated_at = now();

with verified_leagues(code, external_id, external_name) as (
    values
    ('RUSSIAN_FOOTBALL_PREMIER_LEAGUE', '4355', 'Russian Football Premier League'),
    ('ITALIAN_SERIE_B', '4394', 'Italian Serie B'),
    ('SCOTTISH_CHAMPIONSHIP', '4395', 'Scottish Championship'),
    ('ENGLISH_LEAGUE_1', '4396', 'English League 1'),
    ('ENGLISH_LEAGUE_2', '4397', 'English League 2'),
    ('ITALIAN_SERIE_C_GIRONE_C', '4398', 'Italian Serie C Girone C'),
    ('GERMAN_2_BUNDESLIGA', '4399', 'German 2. Bundesliga'),
    ('SPANISH_LA_LIGA_2', '4400', 'Spanish La Liga 2'),
    ('FRENCH_LIGUE_2', '4401', 'French Ligue 2'),
    ('SWEDISH_SUPERETTAN', '4403', 'Swedish Superettan'),
    ('NORWEGIAN_1_DIVISJON', '4457', 'Norwegian 1. Divisjon'),
    ('WELSH_PREMIER_LEAGUE', '4472', 'Welsh Premier League'),
    ('UEFA_NATIONS_LEAGUE', '4490', 'UEFA Nations League'),
    ('AFRICAN_CUP_OF_NATIONS', '4496', 'African Cup of Nations'),
    ('COPA_ARGENTINA', '4500', 'Copa Argentina'),
    ('FIFA_CLUB_WORLD_CUP', '4503', 'FIFA Club World Cup'),
    ('SUPERCOPPA_ITALIANA', '4507', 'Supercoppa Italiana'),
    ('TACA_DE_LIGA', '4509', 'Taca de Liga'),
    ('TACA_DE_PORTUGAL', '4510', 'Taca de Portugal'),
    ('SUPERCOPA_DE_ESPANA', '4511', 'Supercopa de Espana'),
    ('UEFA_SUPER_CUP', '4512', 'UEFA Super Cup'),
    ('VENEZUELA_PRIMERA_DIVISION', '4513', 'Venezuela Primera Division'),
    ('AMERICAN_NWSL', '4521', 'American NWSL'),
    ('INTERNATIONAL_FRIENDLIES', '4562', 'International Friendlies'),
    ('UEFA_EUROPEAN_UNDER_21_CHAMPIONSHIP', '4566', 'UEFA European Under-21 Championship'),
    ('CLUB_FRIENDLIES', '4569', 'Club Friendlies'),
    ('FA_COMMUNITY_SHIELD', '4571', 'FA Community Shield'),
    ('ENGLISH_NATIONAL_LEAGUE', '4590', 'English National League'),
    ('ARGENTINIAN_PRIMERA_B_NACIONAL', '4616', 'Argentinian Primera B Nacional'),
    ('ALBANIAN_SUPERLIGA', '4617', 'Albanian Superliga'),
    ('ANDORRAN_1A_DIVISIO', '4618', 'Andorran 1a Divisio'),
    ('ARMENIAN_PREMIER_LEAGUE', '4619', 'Armenian Premier League'),
    ('AUSTRALIA_ACT_NPL', '4620', 'Australia ACT NPL'),
    ('BELARUS_VYSCHA_LIGA', '4622', 'Belarus Vyscha Liga'),
    ('BELGIAN_CHALLENGER_PRO_LEAGUE', '4623', 'Belgian Challenger Pro League'),
    ('BOSNIAN_PREMIER_LIGA', '4624', 'Bosnian Premier Liga'),
    ('BULGARIAN_FIRST_LEAGUE', '4626', 'Bulgarian First League'),
    ('CHINA_LEAGUE_ONE', '4628', 'China League One'),
    ('CYPRIOT_FIRST_DIVISION', '4630', 'Cypriot First Division'),
    ('DANISH_2ND_DIVISION', '4632', 'Danish 2nd Division'),
    ('FAROE_ISLANDS_PREMIER_LEAGUE', '4635', 'Faroe Islands Premier League'),
    ('FRENCH_LIGUE_3', '4637', 'French Ligue 3'),
    ('GEORGIAN_EROVNULI_LIGA', '4638', 'Georgian Erovnuli Liga'),
    ('GERMANY_LIGA_3', '4639', 'Germany Liga 3'),
    ('GREEK_SUPER_LEAGUE_2', '4640', 'Greek Super League 2'),
    ('DUTCH_EERSTE_DIVISIE', '4641', 'Dutch Eerste Divisie'),
    ('ISRAELI_PREMIER_LEAGUE', '4644', 'Israeli Premier League'),
    ('ITALY_SERIE_D_GIRONE_D', '4645', 'Italy Serie D Girone D'),
    ('ENGLISH_NORTHERN_PREMIER_LEAGUE_PREMIER_DIVISION', '4646', 'English Northern Premier League Premier Division'),
    ('ENGLISH_ISTHMIAN_LEAGUE_PREMIER_DIVISION', '4647', 'English Isthmian League Premier Division'),
    ('ENGLISH_SOUTHERN_PREMIER_LEAGUE_SOUTH_DIVISION', '4648', 'English Southern Premier League South Division'),
    ('MACEDONIAN_FIRST_LEAGUE', '4652', 'Macedonian First League'),
    ('MALTESE_PREMIER_LEAGUE', '4653', 'Maltese Premier League'),
    ('MEXICAN_LIGA_DE_EXPANSION_MX', '4654', 'Mexican Liga de Expansion MX'),
    ('MOLDOVAN_NATIONAL_DIVISION', '4655', 'Moldovan National Division'),
    ('MONTENEGRIN_FIRST_LEAGUE', '4656', 'Montenegrin First League'),
    ('MOROCCAN_BOTOLA_2', '4657', 'Moroccan Botola 2'),
    ('NORTHERN_IRISH_PREMIERSHIP', '4659', 'Northern Irish Premiership'),
    ('POLISH_I_LIGA', '4661', 'Polish I liga'),
    ('PORTUGUESE_LIGAPRO', '4662', 'Portuguese LigaPro'),
    ('ROMANIAN_LIGA_II', '4665', 'Romanian Liga II'),
    ('RUSSIAN_FOOTBALL_NATIONAL_LEAGUE', '4666', 'Russian Football National League'),
    ('SAN_MARINO_CAMPIONATO', '4667', 'San-Marino Campionato'),
    ('SCOTTISH_LEAGUE_1', '4669', 'Scottish League 1'),
    ('SCOTTISH_LEAGUE_2', '4670', 'Scottish League 2'),
    ('SWEDISH_DIVISION_1_NORTH', '4674', 'Swedish Division 1 North'),
    ('TURKISH_1_LIG', '4676', 'Turkish 1 Lig'),
    ('UKRAINIAN_FIRST_LEAGUE', '4677', 'Ukrainian First League'),
    ('TURKISH_2_LIG', '4679', 'Turkish 2 Lig'),
    ('ENGLISH_NATIONAL_LEAGUE_NORTH', '4681', 'English National League North'),
    ('ENGLISH_NATIONAL_LEAGUE_SOUTH', '4682', 'English National League South'),
    ('DANISH_1ST_DIVISION', '4683', 'Danish 1st Division'),
    ('BOLIVIAN_PRIMERA_DIVISION', '4685', 'Bolivian Primera Division'),
    ('HUNGARIAN_NB_I', '4690', 'Hungarian NB I'),
    ('SLOVENIAN_1_SNL', '4692', 'Slovenian 1. SNL'),
    ('AZERBAIJANI_PREMIER_LEAGUE', '4693', 'Azerbaijani Premier League'),
    ('LUXEMBOURG_NATIONAL_DIVISION', '4694', 'Luxembourg National Division'),
    ('GERMAN_REGIONALLIGA_NORD', '4695', 'German Regionalliga Nord'),
    ('SWISS_CHALLENGE_LEAGUE', '4713', 'Swiss Challenge League'),
    ('AFC_CHAMPIONS_LEAGUE_ELITE', '4719', 'AFC Champions League Elite'),
    ('CONCACAF_CHAMPIONS_CUP', '4721', 'CONCACAF Champions Cup'),
    ('SCOTTISH_FA_CUP', '4723', 'Scottish FA Cup'),
    ('COPA_DO_BRASIL', '4725', 'Copa do Brasil'),
    ('CONCACAF_CENTRAL_AMERICAN_CUP', '4739', 'CONCACAF Central American Cup'),
    ('IRANIAN_AZADEGAN_LEAGUE', '4741', 'Iranian Azadegan League'),
    ('IRANIAN_PERSIAN_GULF_PRO_LEAGUE', '4742', 'Iranian Persian Gulf Pro League'),
    ('THAI_LEAGUE_2', '4744', 'Thai League 2'),
    ('KENYAN_PREMIER_LEAGUE', '4745', 'Kenyan Premier League'),
    ('GERMAN_REGIONALLIGA_WEST', '4746', 'German Regionalliga West'),
    ('GERMAN_REGIONALLIGA_SUDWEST', '4747', 'German Regionalliga SudWest'),
    ('GERMAN_REGIONALLIGA_BAYERN', '4748', 'German Regionalliga Bayern'),
    ('GERMAN_REGIONALLIGA_NORDOST', '4749', 'German Regionalliga Nordost'),
    ('ALGERIAN_LIGUE_1', '4753', 'Algerian Ligue 1'),
    ('SENEGAL_LIGUE_1', '4754', 'Senegal Ligue 1'),
    ('NORTHERN_IRISH_CHAMPIONSHIP', '4755', 'Northern Irish Championship'),
    ('SVENSKA_CUPEN', '4756', 'Svenska Cupen'),
    ('ITALY_SERIE_D_GIRONE_B', '4778', 'Italy Serie D Girone B'),
    ('ITALY_SERIE_D_GIRONE_C', '4779', 'Italy Serie D Girone C'),
    ('ITALY_SERIE_D_GIRONE_E', '4780', 'Italy Serie D Girone E'),
    ('ITALY_SERIE_D_GIRONE_F', '4782', 'Italy Serie D Girone F')
)
insert into external_source_mappings (
    id,
    source_type,
    entity_type,
    internal_entity_id,
    external_entity_id,
    league_id,
    season,
    status,
    external_name,
    unresolved_reason,
    created_at,
    updated_at
)
select
    gen_random_uuid(),
    'THESPORTSDB',
    'LEAGUE',
    l.id,
    v.external_id,
    l.id,
    null,
    'RESOLVED',
    v.external_name,
    null,
    now(),
    now()
from verified_leagues v
join leagues l on l.code = v.code
on conflict (source_type, entity_type, external_entity_id) do update
set internal_entity_id = excluded.internal_entity_id,
    league_id = excluded.league_id,
    status = 'RESOLVED',
    external_name = excluded.external_name,
    unresolved_reason = null,
    updated_at = now();
